# Netlify configuration file

# Build settings
[build]
  # Directory to publish (output from your build)
  publish = "dist"
  # Build command
  command = "npm run build"

# Redirects and rewrites
[[redirects]]
  # Redirect all paths to index.html for SPA routing
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  # Define headers for all files
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://images.pexels.com https://cdn.sanity.io; font-src 'self'; connect-src 'self' https://*.supabase.co https://*.sanity.io https://*.stripe.com;"

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Special handling for service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"